var DEFAULT_SETTINGS = {
	"PointsName": "Points",
	"TwitchOAuthToken": "",
	"PlaySound": false,
	"InSound": null,
	"OutSound": null,
	"InTransition": "slideInRight",
	"InAttentionAnimation": "pulse",
	"OutTransition": "slideOutRight",
	"OutAttentionAnimation": "pulse",
	"UseRewardBackgroundColor": false,
	"Duration": 5,
	"ImageShape": "circle",
	"Opacity": 100,
	"TitleColor": "rgba(255, 255, 255, 1)",
	"TitleStrokeColor": "rgba(0, 0, 0, 0)",
	"TitleStrokeWidth": 0,
	"NameColor": "rgba(255, 255, 255, 1)",
	"NameStrokeColor": "rgba(0, 0, 0, 0)",
	"NameStrokeWidth": 0,
	"PromptColor": "rgba(255, 255, 255, 1)",
	"PromptStrokeColor": "rgba(0, 0, 0, 0)",
	"PromptStrokeWidth":0,
	"ShowPrompt": true,
	"MessageColor": "rgba(255, 255, 255, 1)",
	"MessageStrokeColor": "rgba(0, 0, 0, 0)",
	"MessageStrokeWidth": 0,
	"ShowMessage": true,
	"PromptFontSize": 1,
	"TitleFontSize": 1,
	"NameFontSize": 1,
	"MessageFontSize": 1,
	"BorderRadius": 0,
	"BorderColor": "rgba(0,0,0,0)",
	"BorderWidth": 0,
	"MinimumCost": 0,
	"AlertBackgroundColor": "rgba(0, 0, 0, 0)"
};
