var DEFAULT_SETTINGS = {
	"PointsName": "Points",
	"OAuthToken": "",
	"IgnoreFulfillment": true,

	"PlaySound": false,
	"InSound": null,
	"OutSound": null,
	"InTransition": "slideInRight",
	"InAttentionAnimation": "pulse",
	"OutTransition": "slideOutRight",
	"OutAttentionAnimation": "pulse",
	"Duration": 5,
	"ImageShape": "circle",
	"Opacity": 100,
	"TitleColor": "rgba(240, 240, 240, 1)",
	"TitleStrokeColor": "#000",
	"TitleStrokeWidth": 1,
	"NameColor": "rgba(240, 240, 240, 1)",
	"NameStrokeColor": "#000",
	"NameStrokeWidth": 1,
	"PromptColor": "rgba(240, 240, 240, 1)",
	"PromptStrokeColor": "#000",
	"PromptStrokeWidth": 1,
	"ShowPrompt": true,
	"MessageColor": "rgba(240, 240, 240, 1)",
	"MessageStrokeColor": "#000",
	"MessageStrokeWidth": 1,
	"ShowMessage": true,
	"PromptFontSize": 1,
	"TitleFontSize": 1,
	"NameFontSize": 1,
	"MessageFontSize": 1,
	"BorderRadius": 10,
	"MinimumCost": 0,

};
